package com.xd.mapper;

import com.xd.entity.BeFormula;

public interface BeFormulaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table be_formula
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table be_formula
     *
     * @mbggenerated
     */
    int insert(BeFormula record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table be_formula
     *
     * @mbggenerated
     */
    int insertSelective(BeFormula record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table be_formula
     *
     * @mbggenerated
     */
    BeFormula selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table be_formula
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BeFormula record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table be_formula
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BeFormula record);
}