package com.xd.mapper;

import com.xd.entity.BeHistory;

public interface BeHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table be_history
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table be_history
     *
     * @mbggenerated
     */
    int insert(BeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table be_history
     *
     * @mbggenerated
     */
    int insertSelective(BeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table be_history
     *
     * @mbggenerated
     */
    BeHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table be_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table be_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BeHistory record);
}