package com.xd.mapper;

import com.xd.entity.SyArea;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SyAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_area
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_area
     *
     * @mbggenerated
     */
    int insert(SyArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_area
     *
     * @mbggenerated
     */
    int insertSelective(SyArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_area
     *
     * @mbggenerated
     */
    SyArea selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SyArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SyArea record);

    List<SyArea> selectAll();
}