package com.xd.mapper;

import com.xd.entity.SyMenu;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SyMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_menu
     *
     * @mbggenerated
     */
    int insert(SyMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_menu
     *
     * @mbggenerated
     */
    int insertSelective(SyMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_menu
     *
     * @mbggenerated
     */
    SyMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SyMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SyMenu record);

    List<SyMenu> selectAll();
}