package com.xd.service;

import com.xd.entity.SyDept;

import java.util.List;

public interface SyDeptService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_dept
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_dept
     *
     * @mbggenerated
     */
    int insert(SyDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_dept
     *
     * @mbggenerated
     */
    int insertSelective(SyDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_dept
     *
     * @mbggenerated
     */
    SyDept selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_dept
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SyDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_dept
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SyDept record);

    List<SyDept> selectAll();

    List<SyDept> selectByDisabledToSelect();
}
