package com.xd.service;

import com.xd.entity.SyMetertype;

import java.util.List;

public interface SyMetertypeService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_metertype
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_metertype
     *
     * @mbggenerated
     */
    int insert(SyMetertype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_metertype
     *
     * @mbggenerated
     */
    int insertSelective(SyMetertype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_metertype
     *
     * @mbggenerated
     */
    SyMetertype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_metertype
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SyMetertype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_metertype
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SyMetertype record);

    List<SyMetertype> selectAll();

    List<SyMetertype> selectByDisabledYes();
}
