package com.xd.entity;

import java.util.Date;

public class BeComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_comment.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_comment.OrderNo
     *
     * @mbggenerated
     */
    private String orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_comment.Datee
     *
     * @mbggenerated
     */
    private Date datee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_comment.EmpID
     *
     * @mbggenerated
     */
    private Integer empid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_comment.Comment
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_comment.ID
     *
     * @return the value of be_comment.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_comment.ID
     *
     * @param id the value for be_comment.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_comment.OrderNo
     *
     * @return the value of be_comment.OrderNo
     *
     * @mbggenerated
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_comment.OrderNo
     *
     * @param orderno the value for be_comment.OrderNo
     *
     * @mbggenerated
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno == null ? null : orderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_comment.Datee
     *
     * @return the value of be_comment.Datee
     *
     * @mbggenerated
     */
    public Date getDatee() {
        return datee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_comment.Datee
     *
     * @param datee the value for be_comment.Datee
     *
     * @mbggenerated
     */
    public void setDatee(Date datee) {
        this.datee = datee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_comment.EmpID
     *
     * @return the value of be_comment.EmpID
     *
     * @mbggenerated
     */
    public Integer getEmpid() {
        return empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_comment.EmpID
     *
     * @param empid the value for be_comment.EmpID
     *
     * @mbggenerated
     */
    public void setEmpid(Integer empid) {
        this.empid = empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_comment.Comment
     *
     * @return the value of be_comment.Comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_comment.Comment
     *
     * @param comment the value for be_comment.Comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}