package com.xd.entity;

public class BeFlow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_flow.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_flow.StepName
     *
     * @mbggenerated
     */
    private String stepname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_flow.DeptID
     *
     * @mbggenerated
     */
    private Integer deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_flow.Type1
     *
     * @mbggenerated
     */
    private Integer type1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_flow.Type2
     *
     * @mbggenerated
     */
    private Integer type2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_flow.Type3
     *
     * @mbggenerated
     */
    private Integer type3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_flow.Type4
     *
     * @mbggenerated
     */
    private Integer type4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_flow.Type5
     *
     * @mbggenerated
     */
    private Integer type5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_flow.Type6
     *
     * @mbggenerated
     */
    private Integer type6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_flow.Type7
     *
     * @mbggenerated
     */
    private Integer type7;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_flow.ID
     *
     * @return the value of be_flow.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_flow.ID
     *
     * @param id the value for be_flow.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_flow.StepName
     *
     * @return the value of be_flow.StepName
     *
     * @mbggenerated
     */
    public String getStepname() {
        return stepname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_flow.StepName
     *
     * @param stepname the value for be_flow.StepName
     *
     * @mbggenerated
     */
    public void setStepname(String stepname) {
        this.stepname = stepname == null ? null : stepname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_flow.DeptID
     *
     * @return the value of be_flow.DeptID
     *
     * @mbggenerated
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_flow.DeptID
     *
     * @param deptid the value for be_flow.DeptID
     *
     * @mbggenerated
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_flow.Type1
     *
     * @return the value of be_flow.Type1
     *
     * @mbggenerated
     */
    public Integer getType1() {
        return type1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_flow.Type1
     *
     * @param type1 the value for be_flow.Type1
     *
     * @mbggenerated
     */
    public void setType1(Integer type1) {
        this.type1 = type1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_flow.Type2
     *
     * @return the value of be_flow.Type2
     *
     * @mbggenerated
     */
    public Integer getType2() {
        return type2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_flow.Type2
     *
     * @param type2 the value for be_flow.Type2
     *
     * @mbggenerated
     */
    public void setType2(Integer type2) {
        this.type2 = type2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_flow.Type3
     *
     * @return the value of be_flow.Type3
     *
     * @mbggenerated
     */
    public Integer getType3() {
        return type3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_flow.Type3
     *
     * @param type3 the value for be_flow.Type3
     *
     * @mbggenerated
     */
    public void setType3(Integer type3) {
        this.type3 = type3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_flow.Type4
     *
     * @return the value of be_flow.Type4
     *
     * @mbggenerated
     */
    public Integer getType4() {
        return type4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_flow.Type4
     *
     * @param type4 the value for be_flow.Type4
     *
     * @mbggenerated
     */
    public void setType4(Integer type4) {
        this.type4 = type4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_flow.Type5
     *
     * @return the value of be_flow.Type5
     *
     * @mbggenerated
     */
    public Integer getType5() {
        return type5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_flow.Type5
     *
     * @param type5 the value for be_flow.Type5
     *
     * @mbggenerated
     */
    public void setType5(Integer type5) {
        this.type5 = type5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_flow.Type6
     *
     * @return the value of be_flow.Type6
     *
     * @mbggenerated
     */
    public Integer getType6() {
        return type6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_flow.Type6
     *
     * @param type6 the value for be_flow.Type6
     *
     * @mbggenerated
     */
    public void setType6(Integer type6) {
        this.type6 = type6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_flow.Type7
     *
     * @return the value of be_flow.Type7
     *
     * @mbggenerated
     */
    public Integer getType7() {
        return type7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_flow.Type7
     *
     * @param type7 the value for be_flow.Type7
     *
     * @mbggenerated
     */
    public void setType7(Integer type7) {
        this.type7 = type7;
    }
}