package com.xd.entity;

public class BeFormula {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_formula.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_formula.OrderUserID
     *
     * @mbggenerated
     */
    private Integer orderuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_formula.WaterTypeCode
     *
     * @mbggenerated
     */
    private String watertypecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_formula.AllotText
     *
     * @mbggenerated
     */
    private String allottext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_formula.AllotType
     *
     * @mbggenerated
     */
    private Integer allottype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_formula.AllotValue
     *
     * @mbggenerated
     */
    private Integer allotvalue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_formula.ID
     *
     * @return the value of be_formula.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_formula.ID
     *
     * @param id the value for be_formula.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_formula.OrderUserID
     *
     * @return the value of be_formula.OrderUserID
     *
     * @mbggenerated
     */
    public Integer getOrderuserid() {
        return orderuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_formula.OrderUserID
     *
     * @param orderuserid the value for be_formula.OrderUserID
     *
     * @mbggenerated
     */
    public void setOrderuserid(Integer orderuserid) {
        this.orderuserid = orderuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_formula.WaterTypeCode
     *
     * @return the value of be_formula.WaterTypeCode
     *
     * @mbggenerated
     */
    public String getWatertypecode() {
        return watertypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_formula.WaterTypeCode
     *
     * @param watertypecode the value for be_formula.WaterTypeCode
     *
     * @mbggenerated
     */
    public void setWatertypecode(String watertypecode) {
        this.watertypecode = watertypecode == null ? null : watertypecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_formula.AllotText
     *
     * @return the value of be_formula.AllotText
     *
     * @mbggenerated
     */
    public String getAllottext() {
        return allottext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_formula.AllotText
     *
     * @param allottext the value for be_formula.AllotText
     *
     * @mbggenerated
     */
    public void setAllottext(String allottext) {
        this.allottext = allottext == null ? null : allottext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_formula.AllotType
     *
     * @return the value of be_formula.AllotType
     *
     * @mbggenerated
     */
    public Integer getAllottype() {
        return allottype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_formula.AllotType
     *
     * @param allottype the value for be_formula.AllotType
     *
     * @mbggenerated
     */
    public void setAllottype(Integer allottype) {
        this.allottype = allottype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_formula.AllotValue
     *
     * @return the value of be_formula.AllotValue
     *
     * @mbggenerated
     */
    public Integer getAllotvalue() {
        return allotvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_formula.AllotValue
     *
     * @param allotvalue the value for be_formula.AllotValue
     *
     * @mbggenerated
     */
    public void setAllotvalue(Integer allotvalue) {
        this.allotvalue = allotvalue;
    }
}