package com.xd.entity;

import java.util.Date;

public class BeHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_history.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_history.OrderNo
     *
     * @mbggenerated
     */
    private String orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_history.StepID
     *
     * @mbggenerated
     */
    private Integer stepid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_history.Datee
     *
     * @mbggenerated
     */
    private Date datee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_history.EmpID
     *
     * @mbggenerated
     */
    private Integer empid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_history.IsBack
     *
     * @mbggenerated
     */
    private Boolean isback;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_history.ID
     *
     * @return the value of be_history.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_history.ID
     *
     * @param id the value for be_history.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_history.OrderNo
     *
     * @return the value of be_history.OrderNo
     *
     * @mbggenerated
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_history.OrderNo
     *
     * @param orderno the value for be_history.OrderNo
     *
     * @mbggenerated
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno == null ? null : orderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_history.StepID
     *
     * @return the value of be_history.StepID
     *
     * @mbggenerated
     */
    public Integer getStepid() {
        return stepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_history.StepID
     *
     * @param stepid the value for be_history.StepID
     *
     * @mbggenerated
     */
    public void setStepid(Integer stepid) {
        this.stepid = stepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_history.Datee
     *
     * @return the value of be_history.Datee
     *
     * @mbggenerated
     */
    public Date getDatee() {
        return datee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_history.Datee
     *
     * @param datee the value for be_history.Datee
     *
     * @mbggenerated
     */
    public void setDatee(Date datee) {
        this.datee = datee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_history.EmpID
     *
     * @return the value of be_history.EmpID
     *
     * @mbggenerated
     */
    public Integer getEmpid() {
        return empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_history.EmpID
     *
     * @param empid the value for be_history.EmpID
     *
     * @mbggenerated
     */
    public void setEmpid(Integer empid) {
        this.empid = empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_history.IsBack
     *
     * @return the value of be_history.IsBack
     *
     * @mbggenerated
     */
    public Boolean getIsback() {
        return isback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_history.IsBack
     *
     * @param isback the value for be_history.IsBack
     *
     * @mbggenerated
     */
    public void setIsback(Boolean isback) {
        this.isback = isback;
    }
}