package com.xd.entity;

import java.util.Date;

public class BeOrderlite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_orderlite.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_orderlite.OrderType
     *
     * @mbggenerated
     */
    private Integer ordertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_orderlite.Datee
     *
     * @mbggenerated
     */
    private Date datee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_orderlite.EmpID
     *
     * @mbggenerated
     */
    private Integer empid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_orderlite.UserNo
     *
     * @mbggenerated
     */
    private String userno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_orderlite.UserName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_orderlite.Description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_orderlite.ID
     *
     * @return the value of be_orderlite.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_orderlite.ID
     *
     * @param id the value for be_orderlite.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_orderlite.OrderType
     *
     * @return the value of be_orderlite.OrderType
     *
     * @mbggenerated
     */
    public Integer getOrdertype() {
        return ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_orderlite.OrderType
     *
     * @param ordertype the value for be_orderlite.OrderType
     *
     * @mbggenerated
     */
    public void setOrdertype(Integer ordertype) {
        this.ordertype = ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_orderlite.Datee
     *
     * @return the value of be_orderlite.Datee
     *
     * @mbggenerated
     */
    public Date getDatee() {
        return datee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_orderlite.Datee
     *
     * @param datee the value for be_orderlite.Datee
     *
     * @mbggenerated
     */
    public void setDatee(Date datee) {
        this.datee = datee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_orderlite.EmpID
     *
     * @return the value of be_orderlite.EmpID
     *
     * @mbggenerated
     */
    public Integer getEmpid() {
        return empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_orderlite.EmpID
     *
     * @param empid the value for be_orderlite.EmpID
     *
     * @mbggenerated
     */
    public void setEmpid(Integer empid) {
        this.empid = empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_orderlite.UserNo
     *
     * @return the value of be_orderlite.UserNo
     *
     * @mbggenerated
     */
    public String getUserno() {
        return userno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_orderlite.UserNo
     *
     * @param userno the value for be_orderlite.UserNo
     *
     * @mbggenerated
     */
    public void setUserno(String userno) {
        this.userno = userno == null ? null : userno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_orderlite.UserName
     *
     * @return the value of be_orderlite.UserName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_orderlite.UserName
     *
     * @param username the value for be_orderlite.UserName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_orderlite.Description
     *
     * @return the value of be_orderlite.Description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_orderlite.Description
     *
     * @param description the value for be_orderlite.Description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}