package com.xd.entity;

import java.math.BigDecimal;
import java.util.Date;

public class BeOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.OrderNo
     *
     * @mbggenerated
     */
    private String orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.OrderType
     *
     * @mbggenerated
     */
    private Integer ordertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.StepID
     *
     * @mbggenerated
     */
    private Integer stepid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.CreateEmp
     *
     * @mbggenerated
     */
    private Integer createemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.CreateDate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.CompleteEmp
     *
     * @mbggenerated
     */
    private Integer completeemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.CompleteDate
     *
     * @mbggenerated
     */
    private Date completedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.LastEditEmp
     *
     * @mbggenerated
     */
    private Integer lasteditemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.LastEditDate
     *
     * @mbggenerated
     */
    private Date lasteditdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.UserName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.UserType
     *
     * @mbggenerated
     */
    private String usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.Address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.LinkMan
     *
     * @mbggenerated
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.Phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.UseTarget
     *
     * @mbggenerated
     */
    private String usetarget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.HouseHeight
     *
     * @mbggenerated
     */
    private Integer househeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.MaxAmount
     *
     * @mbggenerated
     */
    private Integer maxamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.MeterTypeID
     *
     * @mbggenerated
     */
    private Integer metertypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.MeterCount
     *
     * @mbggenerated
     */
    private Integer metercount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.UserRemark
     *
     * @mbggenerated
     */
    private String userremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.PayType
     *
     * @mbggenerated
     */
    private String paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.BankCompany
     *
     * @mbggenerated
     */
    private String bankcompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.BankNum
     *
     * @mbggenerated
     */
    private String banknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.OldUserNo
     *
     * @mbggenerated
     */
    private String olduserno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.OldUserName
     *
     * @mbggenerated
     */
    private String oldusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.OldUserPhone
     *
     * @mbggenerated
     */
    private String olduserphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.OldUserAddr
     *
     * @mbggenerated
     */
    private String olduseraddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.OldMeter
     *
     * @mbggenerated
     */
    private String oldmeter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.AuditEmpID
     *
     * @mbggenerated
     */
    private Integer auditempid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.AuditMessage
     *
     * @mbggenerated
     */
    private String auditmessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.ProjectMoney
     *
     * @mbggenerated
     */
    private BigDecimal projectmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.RealMoney
     *
     * @mbggenerated
     */
    private BigDecimal realmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.PayDate
     *
     * @mbggenerated
     */
    private Date paydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.ProjectDate1
     *
     * @mbggenerated
     */
    private Date projectdate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.ProjectDate2
     *
     * @mbggenerated
     */
    private Date projectdate2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.AreaID
     *
     * @mbggenerated
     */
    private Integer areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_order.AbortCause
     *
     * @mbggenerated
     */
    private String abortcause;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.OrderNo
     *
     * @return the value of be_order.OrderNo
     *
     * @mbggenerated
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.OrderNo
     *
     * @param orderno the value for be_order.OrderNo
     *
     * @mbggenerated
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno == null ? null : orderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.OrderType
     *
     * @return the value of be_order.OrderType
     *
     * @mbggenerated
     */
    public Integer getOrdertype() {
        return ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.OrderType
     *
     * @param ordertype the value for be_order.OrderType
     *
     * @mbggenerated
     */
    public void setOrdertype(Integer ordertype) {
        this.ordertype = ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.StepID
     *
     * @return the value of be_order.StepID
     *
     * @mbggenerated
     */
    public Integer getStepid() {
        return stepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.StepID
     *
     * @param stepid the value for be_order.StepID
     *
     * @mbggenerated
     */
    public void setStepid(Integer stepid) {
        this.stepid = stepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.CreateEmp
     *
     * @return the value of be_order.CreateEmp
     *
     * @mbggenerated
     */
    public Integer getCreateemp() {
        return createemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.CreateEmp
     *
     * @param createemp the value for be_order.CreateEmp
     *
     * @mbggenerated
     */
    public void setCreateemp(Integer createemp) {
        this.createemp = createemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.CreateDate
     *
     * @return the value of be_order.CreateDate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.CreateDate
     *
     * @param createdate the value for be_order.CreateDate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.CompleteEmp
     *
     * @return the value of be_order.CompleteEmp
     *
     * @mbggenerated
     */
    public Integer getCompleteemp() {
        return completeemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.CompleteEmp
     *
     * @param completeemp the value for be_order.CompleteEmp
     *
     * @mbggenerated
     */
    public void setCompleteemp(Integer completeemp) {
        this.completeemp = completeemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.CompleteDate
     *
     * @return the value of be_order.CompleteDate
     *
     * @mbggenerated
     */
    public Date getCompletedate() {
        return completedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.CompleteDate
     *
     * @param completedate the value for be_order.CompleteDate
     *
     * @mbggenerated
     */
    public void setCompletedate(Date completedate) {
        this.completedate = completedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.LastEditEmp
     *
     * @return the value of be_order.LastEditEmp
     *
     * @mbggenerated
     */
    public Integer getLasteditemp() {
        return lasteditemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.LastEditEmp
     *
     * @param lasteditemp the value for be_order.LastEditEmp
     *
     * @mbggenerated
     */
    public void setLasteditemp(Integer lasteditemp) {
        this.lasteditemp = lasteditemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.LastEditDate
     *
     * @return the value of be_order.LastEditDate
     *
     * @mbggenerated
     */
    public Date getLasteditdate() {
        return lasteditdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.LastEditDate
     *
     * @param lasteditdate the value for be_order.LastEditDate
     *
     * @mbggenerated
     */
    public void setLasteditdate(Date lasteditdate) {
        this.lasteditdate = lasteditdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.UserName
     *
     * @return the value of be_order.UserName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.UserName
     *
     * @param username the value for be_order.UserName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.UserType
     *
     * @return the value of be_order.UserType
     *
     * @mbggenerated
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.UserType
     *
     * @param usertype the value for be_order.UserType
     *
     * @mbggenerated
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype == null ? null : usertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.Address
     *
     * @return the value of be_order.Address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.Address
     *
     * @param address the value for be_order.Address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.LinkMan
     *
     * @return the value of be_order.LinkMan
     *
     * @mbggenerated
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.LinkMan
     *
     * @param linkman the value for be_order.LinkMan
     *
     * @mbggenerated
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.Phone
     *
     * @return the value of be_order.Phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.Phone
     *
     * @param phone the value for be_order.Phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.UseTarget
     *
     * @return the value of be_order.UseTarget
     *
     * @mbggenerated
     */
    public String getUsetarget() {
        return usetarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.UseTarget
     *
     * @param usetarget the value for be_order.UseTarget
     *
     * @mbggenerated
     */
    public void setUsetarget(String usetarget) {
        this.usetarget = usetarget == null ? null : usetarget.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.HouseHeight
     *
     * @return the value of be_order.HouseHeight
     *
     * @mbggenerated
     */
    public Integer getHouseheight() {
        return househeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.HouseHeight
     *
     * @param househeight the value for be_order.HouseHeight
     *
     * @mbggenerated
     */
    public void setHouseheight(Integer househeight) {
        this.househeight = househeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.MaxAmount
     *
     * @return the value of be_order.MaxAmount
     *
     * @mbggenerated
     */
    public Integer getMaxamount() {
        return maxamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.MaxAmount
     *
     * @param maxamount the value for be_order.MaxAmount
     *
     * @mbggenerated
     */
    public void setMaxamount(Integer maxamount) {
        this.maxamount = maxamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.MeterTypeID
     *
     * @return the value of be_order.MeterTypeID
     *
     * @mbggenerated
     */
    public Integer getMetertypeid() {
        return metertypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.MeterTypeID
     *
     * @param metertypeid the value for be_order.MeterTypeID
     *
     * @mbggenerated
     */
    public void setMetertypeid(Integer metertypeid) {
        this.metertypeid = metertypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.MeterCount
     *
     * @return the value of be_order.MeterCount
     *
     * @mbggenerated
     */
    public Integer getMetercount() {
        return metercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.MeterCount
     *
     * @param metercount the value for be_order.MeterCount
     *
     * @mbggenerated
     */
    public void setMetercount(Integer metercount) {
        this.metercount = metercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.UserRemark
     *
     * @return the value of be_order.UserRemark
     *
     * @mbggenerated
     */
    public String getUserremark() {
        return userremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.UserRemark
     *
     * @param userremark the value for be_order.UserRemark
     *
     * @mbggenerated
     */
    public void setUserremark(String userremark) {
        this.userremark = userremark == null ? null : userremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.PayType
     *
     * @return the value of be_order.PayType
     *
     * @mbggenerated
     */
    public String getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.PayType
     *
     * @param paytype the value for be_order.PayType
     *
     * @mbggenerated
     */
    public void setPaytype(String paytype) {
        this.paytype = paytype == null ? null : paytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.BankCompany
     *
     * @return the value of be_order.BankCompany
     *
     * @mbggenerated
     */
    public String getBankcompany() {
        return bankcompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.BankCompany
     *
     * @param bankcompany the value for be_order.BankCompany
     *
     * @mbggenerated
     */
    public void setBankcompany(String bankcompany) {
        this.bankcompany = bankcompany == null ? null : bankcompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.BankNum
     *
     * @return the value of be_order.BankNum
     *
     * @mbggenerated
     */
    public String getBanknum() {
        return banknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.BankNum
     *
     * @param banknum the value for be_order.BankNum
     *
     * @mbggenerated
     */
    public void setBanknum(String banknum) {
        this.banknum = banknum == null ? null : banknum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.OldUserNo
     *
     * @return the value of be_order.OldUserNo
     *
     * @mbggenerated
     */
    public String getOlduserno() {
        return olduserno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.OldUserNo
     *
     * @param olduserno the value for be_order.OldUserNo
     *
     * @mbggenerated
     */
    public void setOlduserno(String olduserno) {
        this.olduserno = olduserno == null ? null : olduserno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.OldUserName
     *
     * @return the value of be_order.OldUserName
     *
     * @mbggenerated
     */
    public String getOldusername() {
        return oldusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.OldUserName
     *
     * @param oldusername the value for be_order.OldUserName
     *
     * @mbggenerated
     */
    public void setOldusername(String oldusername) {
        this.oldusername = oldusername == null ? null : oldusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.OldUserPhone
     *
     * @return the value of be_order.OldUserPhone
     *
     * @mbggenerated
     */
    public String getOlduserphone() {
        return olduserphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.OldUserPhone
     *
     * @param olduserphone the value for be_order.OldUserPhone
     *
     * @mbggenerated
     */
    public void setOlduserphone(String olduserphone) {
        this.olduserphone = olduserphone == null ? null : olduserphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.OldUserAddr
     *
     * @return the value of be_order.OldUserAddr
     *
     * @mbggenerated
     */
    public String getOlduseraddr() {
        return olduseraddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.OldUserAddr
     *
     * @param olduseraddr the value for be_order.OldUserAddr
     *
     * @mbggenerated
     */
    public void setOlduseraddr(String olduseraddr) {
        this.olduseraddr = olduseraddr == null ? null : olduseraddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.OldMeter
     *
     * @return the value of be_order.OldMeter
     *
     * @mbggenerated
     */
    public String getOldmeter() {
        return oldmeter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.OldMeter
     *
     * @param oldmeter the value for be_order.OldMeter
     *
     * @mbggenerated
     */
    public void setOldmeter(String oldmeter) {
        this.oldmeter = oldmeter == null ? null : oldmeter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.AuditEmpID
     *
     * @return the value of be_order.AuditEmpID
     *
     * @mbggenerated
     */
    public Integer getAuditempid() {
        return auditempid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.AuditEmpID
     *
     * @param auditempid the value for be_order.AuditEmpID
     *
     * @mbggenerated
     */
    public void setAuditempid(Integer auditempid) {
        this.auditempid = auditempid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.AuditMessage
     *
     * @return the value of be_order.AuditMessage
     *
     * @mbggenerated
     */
    public String getAuditmessage() {
        return auditmessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.AuditMessage
     *
     * @param auditmessage the value for be_order.AuditMessage
     *
     * @mbggenerated
     */
    public void setAuditmessage(String auditmessage) {
        this.auditmessage = auditmessage == null ? null : auditmessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.ProjectMoney
     *
     * @return the value of be_order.ProjectMoney
     *
     * @mbggenerated
     */
    public BigDecimal getProjectmoney() {
        return projectmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.ProjectMoney
     *
     * @param projectmoney the value for be_order.ProjectMoney
     *
     * @mbggenerated
     */
    public void setProjectmoney(BigDecimal projectmoney) {
        this.projectmoney = projectmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.RealMoney
     *
     * @return the value of be_order.RealMoney
     *
     * @mbggenerated
     */
    public BigDecimal getRealmoney() {
        return realmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.RealMoney
     *
     * @param realmoney the value for be_order.RealMoney
     *
     * @mbggenerated
     */
    public void setRealmoney(BigDecimal realmoney) {
        this.realmoney = realmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.PayDate
     *
     * @return the value of be_order.PayDate
     *
     * @mbggenerated
     */
    public Date getPaydate() {
        return paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.PayDate
     *
     * @param paydate the value for be_order.PayDate
     *
     * @mbggenerated
     */
    public void setPaydate(Date paydate) {
        this.paydate = paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.ProjectDate1
     *
     * @return the value of be_order.ProjectDate1
     *
     * @mbggenerated
     */
    public Date getProjectdate1() {
        return projectdate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.ProjectDate1
     *
     * @param projectdate1 the value for be_order.ProjectDate1
     *
     * @mbggenerated
     */
    public void setProjectdate1(Date projectdate1) {
        this.projectdate1 = projectdate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.ProjectDate2
     *
     * @return the value of be_order.ProjectDate2
     *
     * @mbggenerated
     */
    public Date getProjectdate2() {
        return projectdate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.ProjectDate2
     *
     * @param projectdate2 the value for be_order.ProjectDate2
     *
     * @mbggenerated
     */
    public void setProjectdate2(Date projectdate2) {
        this.projectdate2 = projectdate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.AreaID
     *
     * @return the value of be_order.AreaID
     *
     * @mbggenerated
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.AreaID
     *
     * @param areaid the value for be_order.AreaID
     *
     * @mbggenerated
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_order.AbortCause
     *
     * @return the value of be_order.AbortCause
     *
     * @mbggenerated
     */
    public String getAbortcause() {
        return abortcause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_order.AbortCause
     *
     * @param abortcause the value for be_order.AbortCause
     *
     * @mbggenerated
     */
    public void setAbortcause(String abortcause) {
        this.abortcause = abortcause == null ? null : abortcause.trim();
    }
}