package com.xd.entity;

import java.math.BigDecimal;

public class BeOrderuser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_orderuser.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_orderuser.OrderNo
     *
     * @mbggenerated
     */
    private String orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_orderuser.UserName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_orderuser.Phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_orderuser.SMSPhone
     *
     * @mbggenerated
     */
    private String smsphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_orderuser.Address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_orderuser.ProjectMoney
     *
     * @mbggenerated
     */
    private BigDecimal projectmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_orderuser.RealMoney
     *
     * @mbggenerated
     */
    private BigDecimal realmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_orderuser.InvoiceNo
     *
     * @mbggenerated
     */
    private String invoiceno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_orderuser.Formula
     *
     * @mbggenerated
     */
    private String formula;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_orderuser.ContractNum
     *
     * @mbggenerated
     */
    private String contractnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_orderuser.MeterTypeID
     *
     * @mbggenerated
     */
    private Integer metertypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_orderuser.MeterName
     *
     * @mbggenerated
     */
    private String metername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_orderuser.MaxValues
     *
     * @mbggenerated
     */
    private Integer maxvalues;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_orderuser.StartValue
     *
     * @mbggenerated
     */
    private Integer startvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_orderuser.MeterFactory
     *
     * @mbggenerated
     */
    private String meterfactory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_orderuser.DocNum
     *
     * @mbggenerated
     */
    private String docnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_orderuser.UserNo
     *
     * @mbggenerated
     */
    private String userno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_orderuser.ID
     *
     * @return the value of be_orderuser.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_orderuser.ID
     *
     * @param id the value for be_orderuser.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_orderuser.OrderNo
     *
     * @return the value of be_orderuser.OrderNo
     *
     * @mbggenerated
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_orderuser.OrderNo
     *
     * @param orderno the value for be_orderuser.OrderNo
     *
     * @mbggenerated
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno == null ? null : orderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_orderuser.UserName
     *
     * @return the value of be_orderuser.UserName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_orderuser.UserName
     *
     * @param username the value for be_orderuser.UserName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_orderuser.Phone
     *
     * @return the value of be_orderuser.Phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_orderuser.Phone
     *
     * @param phone the value for be_orderuser.Phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_orderuser.SMSPhone
     *
     * @return the value of be_orderuser.SMSPhone
     *
     * @mbggenerated
     */
    public String getSmsphone() {
        return smsphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_orderuser.SMSPhone
     *
     * @param smsphone the value for be_orderuser.SMSPhone
     *
     * @mbggenerated
     */
    public void setSmsphone(String smsphone) {
        this.smsphone = smsphone == null ? null : smsphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_orderuser.Address
     *
     * @return the value of be_orderuser.Address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_orderuser.Address
     *
     * @param address the value for be_orderuser.Address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_orderuser.ProjectMoney
     *
     * @return the value of be_orderuser.ProjectMoney
     *
     * @mbggenerated
     */
    public BigDecimal getProjectmoney() {
        return projectmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_orderuser.ProjectMoney
     *
     * @param projectmoney the value for be_orderuser.ProjectMoney
     *
     * @mbggenerated
     */
    public void setProjectmoney(BigDecimal projectmoney) {
        this.projectmoney = projectmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_orderuser.RealMoney
     *
     * @return the value of be_orderuser.RealMoney
     *
     * @mbggenerated
     */
    public BigDecimal getRealmoney() {
        return realmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_orderuser.RealMoney
     *
     * @param realmoney the value for be_orderuser.RealMoney
     *
     * @mbggenerated
     */
    public void setRealmoney(BigDecimal realmoney) {
        this.realmoney = realmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_orderuser.InvoiceNo
     *
     * @return the value of be_orderuser.InvoiceNo
     *
     * @mbggenerated
     */
    public String getInvoiceno() {
        return invoiceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_orderuser.InvoiceNo
     *
     * @param invoiceno the value for be_orderuser.InvoiceNo
     *
     * @mbggenerated
     */
    public void setInvoiceno(String invoiceno) {
        this.invoiceno = invoiceno == null ? null : invoiceno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_orderuser.Formula
     *
     * @return the value of be_orderuser.Formula
     *
     * @mbggenerated
     */
    public String getFormula() {
        return formula;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_orderuser.Formula
     *
     * @param formula the value for be_orderuser.Formula
     *
     * @mbggenerated
     */
    public void setFormula(String formula) {
        this.formula = formula == null ? null : formula.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_orderuser.ContractNum
     *
     * @return the value of be_orderuser.ContractNum
     *
     * @mbggenerated
     */
    public String getContractnum() {
        return contractnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_orderuser.ContractNum
     *
     * @param contractnum the value for be_orderuser.ContractNum
     *
     * @mbggenerated
     */
    public void setContractnum(String contractnum) {
        this.contractnum = contractnum == null ? null : contractnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_orderuser.MeterTypeID
     *
     * @return the value of be_orderuser.MeterTypeID
     *
     * @mbggenerated
     */
    public Integer getMetertypeid() {
        return metertypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_orderuser.MeterTypeID
     *
     * @param metertypeid the value for be_orderuser.MeterTypeID
     *
     * @mbggenerated
     */
    public void setMetertypeid(Integer metertypeid) {
        this.metertypeid = metertypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_orderuser.MeterName
     *
     * @return the value of be_orderuser.MeterName
     *
     * @mbggenerated
     */
    public String getMetername() {
        return metername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_orderuser.MeterName
     *
     * @param metername the value for be_orderuser.MeterName
     *
     * @mbggenerated
     */
    public void setMetername(String metername) {
        this.metername = metername == null ? null : metername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_orderuser.MaxValues
     *
     * @return the value of be_orderuser.MaxValues
     *
     * @mbggenerated
     */
    public Integer getMaxvalues() {
        return maxvalues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_orderuser.MaxValues
     *
     * @param maxvalues the value for be_orderuser.MaxValues
     *
     * @mbggenerated
     */
    public void setMaxvalues(Integer maxvalues) {
        this.maxvalues = maxvalues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_orderuser.StartValue
     *
     * @return the value of be_orderuser.StartValue
     *
     * @mbggenerated
     */
    public Integer getStartvalue() {
        return startvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_orderuser.StartValue
     *
     * @param startvalue the value for be_orderuser.StartValue
     *
     * @mbggenerated
     */
    public void setStartvalue(Integer startvalue) {
        this.startvalue = startvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_orderuser.MeterFactory
     *
     * @return the value of be_orderuser.MeterFactory
     *
     * @mbggenerated
     */
    public String getMeterfactory() {
        return meterfactory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_orderuser.MeterFactory
     *
     * @param meterfactory the value for be_orderuser.MeterFactory
     *
     * @mbggenerated
     */
    public void setMeterfactory(String meterfactory) {
        this.meterfactory = meterfactory == null ? null : meterfactory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_orderuser.DocNum
     *
     * @return the value of be_orderuser.DocNum
     *
     * @mbggenerated
     */
    public String getDocnum() {
        return docnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_orderuser.DocNum
     *
     * @param docnum the value for be_orderuser.DocNum
     *
     * @mbggenerated
     */
    public void setDocnum(String docnum) {
        this.docnum = docnum == null ? null : docnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_orderuser.UserNo
     *
     * @return the value of be_orderuser.UserNo
     *
     * @mbggenerated
     */
    public String getUserno() {
        return userno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_orderuser.UserNo
     *
     * @param userno the value for be_orderuser.UserNo
     *
     * @mbggenerated
     */
    public void setUserno(String userno) {
        this.userno = userno == null ? null : userno.trim();
    }
}