package com.xd.entity;

public class SyArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_area.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_area.AreaName
     *
     * @mbggenerated
     */
    private String areaname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_area.Remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_area.Disabled
     *
     * @mbggenerated
     */
    private Boolean disabled;

    @Override
    public String toString() {
        return "SyArea{" +
                "id=" + id +
                ", areaname='" + areaname + '\'' +
                ", remark='" + remark + '\'' +
                ", disabled=" + disabled +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_area.ID
     *
     * @return the value of sy_area.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_area.ID
     *
     * @param id the value for sy_area.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_area.AreaName
     *
     * @return the value of sy_area.AreaName
     *
     * @mbggenerated
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_area.AreaName
     *
     * @param areaname the value for sy_area.AreaName
     *
     * @mbggenerated
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_area.Remark
     *
     * @return the value of sy_area.Remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_area.Remark
     *
     * @param remark the value for sy_area.Remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_area.Disabled
     *
     * @return the value of sy_area.Disabled
     *
     * @mbggenerated
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_area.Disabled
     *
     * @param disabled the value for sy_area.Disabled
     *
     * @mbggenerated
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }
}