package com.xd.entity;

import java.math.BigDecimal;

public class SyCosttype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_costtype.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_costtype.Kind
     *
     * @mbggenerated
     */
    private Integer kind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_costtype.Code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_costtype.CostTypeName
     *
     * @mbggenerated
     */
    private String costtypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_costtype.FullName
     *
     * @mbggenerated
     */
    private String fullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_costtype.Price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_costtype.SurchargeText
     *
     * @mbggenerated
     */
    private String surchargetext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_costtype.Remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_costtype.Disabled
     *
     * @mbggenerated
     */
    private Boolean disabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_costtype.ID
     *
     * @return the value of sy_costtype.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_costtype.ID
     *
     * @param id the value for sy_costtype.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_costtype.Kind
     *
     * @return the value of sy_costtype.Kind
     *
     * @mbggenerated
     */
    public Integer getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_costtype.Kind
     *
     * @param kind the value for sy_costtype.Kind
     *
     * @mbggenerated
     */
    public void setKind(Integer kind) {
        this.kind = kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_costtype.Code
     *
     * @return the value of sy_costtype.Code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_costtype.Code
     *
     * @param code the value for sy_costtype.Code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_costtype.CostTypeName
     *
     * @return the value of sy_costtype.CostTypeName
     *
     * @mbggenerated
     */
    public String getCosttypename() {
        return costtypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_costtype.CostTypeName
     *
     * @param costtypename the value for sy_costtype.CostTypeName
     *
     * @mbggenerated
     */
    public void setCosttypename(String costtypename) {
        this.costtypename = costtypename == null ? null : costtypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_costtype.FullName
     *
     * @return the value of sy_costtype.FullName
     *
     * @mbggenerated
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_costtype.FullName
     *
     * @param fullname the value for sy_costtype.FullName
     *
     * @mbggenerated
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_costtype.Price
     *
     * @return the value of sy_costtype.Price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_costtype.Price
     *
     * @param price the value for sy_costtype.Price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_costtype.SurchargeText
     *
     * @return the value of sy_costtype.SurchargeText
     *
     * @mbggenerated
     */
    public String getSurchargetext() {
        return surchargetext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_costtype.SurchargeText
     *
     * @param surchargetext the value for sy_costtype.SurchargeText
     *
     * @mbggenerated
     */
    public void setSurchargetext(String surchargetext) {
        this.surchargetext = surchargetext == null ? null : surchargetext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_costtype.Remark
     *
     * @return the value of sy_costtype.Remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_costtype.Remark
     *
     * @param remark the value for sy_costtype.Remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_costtype.Disabled
     *
     * @return the value of sy_costtype.Disabled
     *
     * @mbggenerated
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_costtype.Disabled
     *
     * @param disabled the value for sy_costtype.Disabled
     *
     * @mbggenerated
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }
}