package com.xd.entity;

import java.util.ArrayList;
import java.util.List;

public class SyEmp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_emp.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_emp.EmpName
     *
     * @mbggenerated
     */
    private String empname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_emp.EmpNo
     *
     * @mbggenerated
     */
    private String empno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_emp.Pwd
     *
     * @mbggenerated
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_emp.DeptID
     *
     * @mbggenerated
     */
    private Integer deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_emp.Remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_emp.Disabled
     *
     * @mbggenerated
     */
    private Boolean disabled;

    /**
     * 裁断权限（对多）
     */
    private List<SyMenu> syMenuList = new ArrayList<SyMenu>(0);

    /**
     * 所属部门(对一)
     */
    private SyDept syDept;

    @Override
    public String toString() {
        return "SyEmp{" +
                "id=" + id +
                ", empname='" + empname + '\'' +
                ", empno='" + empno + '\'' +
                ", pwd='" + pwd + '\'' +
                ", deptid=" + deptid +
                ", remark='" + remark + '\'' +
                ", disabled=" + disabled +
                '}';
    }

    public List<SyMenu> getSyMenuList() {
        return syMenuList;
    }

    public void setSyMenuList(List<SyMenu> syMenuList) {
        this.syMenuList = syMenuList;
    }

    public SyDept getSyDept() {
        return syDept;
    }

    public void setSyDept(SyDept syDept) {
        this.syDept = syDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_emp.ID
     *
     * @return the value of sy_emp.ID
     *
     * @mbggenerated
     */

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_emp.ID
     *
     * @param id the value for sy_emp.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_emp.EmpName
     *
     * @return the value of sy_emp.EmpName
     *
     * @mbggenerated
     */
    public String getEmpname() {
        return empname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_emp.EmpName
     *
     * @param empname the value for sy_emp.EmpName
     *
     * @mbggenerated
     */
    public void setEmpname(String empname) {
        this.empname = empname == null ? null : empname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_emp.EmpNo
     *
     * @return the value of sy_emp.EmpNo
     *
     * @mbggenerated
     */
    public String getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_emp.EmpNo
     *
     * @param empno the value for sy_emp.EmpNo
     *
     * @mbggenerated
     */
    public void setEmpno(String empno) {
        this.empno = empno == null ? null : empno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_emp.Pwd
     *
     * @return the value of sy_emp.Pwd
     *
     * @mbggenerated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_emp.Pwd
     *
     * @param pwd the value for sy_emp.Pwd
     *
     * @mbggenerated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_emp.DeptID
     *
     * @return the value of sy_emp.DeptID
     *
     * @mbggenerated
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_emp.DeptID
     *
     * @param deptid the value for sy_emp.DeptID
     *
     * @mbggenerated
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_emp.Remark
     *
     * @return the value of sy_emp.Remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_emp.Remark
     *
     * @param remark the value for sy_emp.Remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_emp.Disabled
     *
     * @return the value of sy_emp.Disabled
     *
     * @mbggenerated
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_emp.Disabled
     *
     * @param disabled the value for sy_emp.Disabled
     *
     * @mbggenerated
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }
}