package com.xd.entity;

public class SyMetertype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_metertype.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_metertype.MeterTypeName
     *
     * @mbggenerated
     */
    private String metertypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_metertype.Aperture
     *
     * @mbggenerated
     */
    private Integer aperture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_metertype.MavValue
     *
     * @mbggenerated
     */
    private Integer mavvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_metertype.MinValue
     *
     * @mbggenerated
     */
    private Integer minvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_metertype.Life
     *
     * @mbggenerated
     */
    private Integer life;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_metertype.Remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_metertype.Disabled
     *
     * @mbggenerated
     */
    private Boolean disabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_metertype.ID
     *
     * @return the value of sy_metertype.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_metertype.ID
     *
     * @param id the value for sy_metertype.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_metertype.MeterTypeName
     *
     * @return the value of sy_metertype.MeterTypeName
     *
     * @mbggenerated
     */
    public String getMetertypename() {
        return metertypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_metertype.MeterTypeName
     *
     * @param metertypename the value for sy_metertype.MeterTypeName
     *
     * @mbggenerated
     */
    public void setMetertypename(String metertypename) {
        this.metertypename = metertypename == null ? null : metertypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_metertype.Aperture
     *
     * @return the value of sy_metertype.Aperture
     *
     * @mbggenerated
     */
    public Integer getAperture() {
        return aperture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_metertype.Aperture
     *
     * @param aperture the value for sy_metertype.Aperture
     *
     * @mbggenerated
     */
    public void setAperture(Integer aperture) {
        this.aperture = aperture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_metertype.MavValue
     *
     * @return the value of sy_metertype.MavValue
     *
     * @mbggenerated
     */
    public Integer getMavvalue() {
        return mavvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_metertype.MavValue
     *
     * @param mavvalue the value for sy_metertype.MavValue
     *
     * @mbggenerated
     */
    public void setMavvalue(Integer mavvalue) {
        this.mavvalue = mavvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_metertype.MinValue
     *
     * @return the value of sy_metertype.MinValue
     *
     * @mbggenerated
     */
    public Integer getMinvalue() {
        return minvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_metertype.MinValue
     *
     * @param minvalue the value for sy_metertype.MinValue
     *
     * @mbggenerated
     */
    public void setMinvalue(Integer minvalue) {
        this.minvalue = minvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_metertype.Life
     *
     * @return the value of sy_metertype.Life
     *
     * @mbggenerated
     */
    public Integer getLife() {
        return life;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_metertype.Life
     *
     * @param life the value for sy_metertype.Life
     *
     * @mbggenerated
     */
    public void setLife(Integer life) {
        this.life = life;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_metertype.Remark
     *
     * @return the value of sy_metertype.Remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_metertype.Remark
     *
     * @param remark the value for sy_metertype.Remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_metertype.Disabled
     *
     * @return the value of sy_metertype.Disabled
     *
     * @mbggenerated
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_metertype.Disabled
     *
     * @param disabled the value for sy_metertype.Disabled
     *
     * @mbggenerated
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }
}